### ISSUE TITLE
Function errors maybe

### ISSUE THREAD

**Issue by TobMTV** [zedd3v/abck#4]
I was reading that function (cc) , but i think the var k and l are not right like that, check it please.

https://github.com/zedd3v/abck/blob/06282aca9dc42019285f10fcb8edb6d3bd6c8f45/src/index.ts#L127

**Comment by zedd3v** [comment]
Where is the error? Can you please give more details or make a repo showing the error?

**Comment by TobMTV** [comment]
yep, l and k are not related to any parameters, maybe you are referring to t and a.

**Comment by ShRyDeR** [comment]
@TobMTV the variable n is a function, _l and _k are that function's parameters. They are not supposed to be defined outside the function.
