### ISSUE TITLE
How use this lib?

### ISSUE THREAD

**Issue by cybopob93** [zedd3v/abck#5]
This is description:
"Abck is a library that makes generating akamai cookies easier."

Here has example of using:

`
const d3 = Abck.d3();

Abck.gd(Date.now(), d3, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36", {
  availWidth: 1680,
  availHeight: 972,
  width: 1680,
  height: 1050,
  innerWidth: 1680,
  innerHeight: 939,
  outerWidth: 1680,
});
`

I install this lib, but when i try use example i got exeption like 'd3 is not defined'. Lib in develop at this moment?

**Comment by zedd3v** [comment]
The library was updated.
Please check the new readme for the list of functions and arguments

**Comment by cybopob93** [comment]
Can you add to readme examle of usage? Something like:
to generate first sensor_data you need do next steps:

`
import Abck from 'abck';

let sensorData = `${Abck.get_cf_date()},${Abck.x2()}`
`
Because i don't understand how it use :) i don't understand, for example, what i need put to ff() method and where to substitute the obtained values.

Its realy good potential in this solution, but i can't understand how it use. If you needs some help with it - I will gladly help if it is in my power

**Comment by zedd3v** [comment]
I can only help so much
If you dont know how to utilize the functions you need to do more research

**Comment by cybopob93** [comment]
I understand. 
Correctly I understand that i need use this lib like:

`bmak.sed = Abck.sed`
`let sensorData = bmak.get_telemetry() || bmak.sensor_data`

Just set lib like interceptors to original script, for generation original sensor data?
